server:
  port: 8221

spring:
  application:
    name: user-rs
  main:
    banner-mode: off
  datasource:
    url: jdbc:log4jdbc:h2:file:~/h2db/app_user;AUTO_SERVER=true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console

system:
  api:
    board: http://localhost:8220/board
